### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by dconner3** [OpenCon-Cascadia/planning_in_the_open#8]
A place to start drafting a Code of Conduct for the conference. 

Last year, there was [a really great conference](https://csvconf.com/) in town that used this [Code of Conduct](http://confcodeofconduct.com/). Perhaps a sub-group could review this and see if it  meets our mission / needs any edits or additions?

Also, this was suggested by @ashleyfarley on another issue:
Maybe the following can be part of a Code of Conduct to provide more details on DEI:
Regardless of race, ethnicity, gender, nationality, religious and political views, and other aspects of their identities, individuals are included based on their enormous potential to contribute to the community. It is imperative that all participants—and, indeed, all members of our OpenCon Cascadia community—are valued, respected, and provided with equal opportunities to thrive.

**Comment by ashleyfarley** [comment]
I've set up a section titled "Code of Conduct" in the Google Doc Appendix for working text edits.

**Comment by dasaderi** [comment]
Thank you @ashleyfarley! 

As I suggested in the doc, we can always use [OpenCon's CoC](https://www.opencon2018.org/code_of_conduct). Also we should have a safety team, usually 2 organizers. I volunteer to be one as I have done it in the past.

**Comment by ashleyfarley** [comment]
I believe that this component is complete. Please review, make any changes, or make comments. For a better formatted version please see the Google Doc. 
_____________________________________________________________________________________
Code of Conduct 
All attendees, speakers, and organizers at our OpenCon Cascadia are required to follow the following code of conduct. Organizers will enforce this code throughout the entire event. We expect cooperation from all participants to help ensure a safe environment for everyone.
OpenCon Community Values 
Our community strives to:
Be friendly and patient.
Be welcoming: We strive to be a community that welcomes and supports people of all backgrounds and identities. This includes, but is not limited to, members of any race, ethnicity, culture, national origin, immigration status, social and economic class, educational level, sex, sexual orientation, gender identity and expression, age, size, family status, political belief, religion, and mental and physical ability.
Be considerate: Your work will be used by other people, and you in turn will depend on the work of others. Any decision you take will affect colleagues, and you should take those consequences into account when making decisions. Remember that we’re a worldwide community, so you might not be communicating in someone else’s primary language.
Be respectful: Not all of us will agree all the time, but disagreement is no excuse for poor behavior and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack. It’s important to remember that a community where people feel uncomfortable or threatened is not a productive one.
Be careful in the words that we choose: we are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behavior aren’t acceptable.
Try to understand why we disagree: Disagreements, both social and technical, happen all the time. It is important that we resolve disagreements and differing views constructively. Remember that we’re different. The strength of our community comes from its diversity. Different people have different perspectives on issues. Being unable to understand why someone holds a viewpoint doesn’t mean that they’re wrong. Don’t forget that it is human to err and blaming each other doesn’t get us anywhere. Instead, focus on helping to resolve issues and learning from mistakes.


Our conference is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form from anyone. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, and social media. Conference participants violating these rules may be sanctioned or expelled from the conference at the discretion of the conference organizers.

Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately. 

We expect participants to follow these rules at conference and workshop venues and conference-related social events.

Ask for consent (i.e. permission), and respect people’s boundaries.
Ask for permission before you engage in physical interactions with participants (this applies to everything from friendly interactions, such as asking “Can I hug you?” before you hug someone—to sexual attention and/or sexualized physical contact at conference social events or after hours, off-site). If they say no, respect that and don’t continue. Sexual harassment is unacceptable, including on online, at conference social events, and after-hours at the conference.
Be careful about the words you use. Is the language that you’re using discriminatory?
There is a lot of everyday language which discriminates against people. Using racial slurs, or phrases like “that’s lame”, “that’s gay”, or “that’s retarded” may seem harmless to some, but actually discriminates against minorities such as people of colour, LGBTQ+ people, or those with disabilities. If someone calls you out for using problematic language, please take the time to listen, apologize, and put effort into not using the language again. You may be asked to leave the community for using this kind of language.
Be mindful of how much time and space you’re taking up. Be aware of your power and privilege, and whether you’re taking advantage of it.
Are you a man who is taking up all the time for questions in a workshop full of mostly female participants? Are you a Western academic who isn’t giving a chance for a participant from an underrepresented country to speak? Are you attempting to engage in a physical or intimate interaction with someone who doesn’t have the capacity to consent? (E.g. at an evening social event with alcohol). Are you taking the time to listen to the perspectives of those who are different from you?

Diversity Statement
Regardless of race, ethnicity, gender, nationality, religious and political views, and other aspects of their identities, individuals are invited based on their enormous potential to contribute to the community. It is imperative that all participants—and, indeed, all members of our OpenCon Cascadia community—are valued, respected, and provided with equal opportunities to thrive.

Definitions
Harassment includes, but is not limited to:
Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, race, age, regional discrimination, political or religious affiliation
Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment
Deliberate misgendering. This includes deadnaming or persistently using a pronoun that does not correctly reflect a person’s gender identity. You must address people by the name they give you when not addressing them by their username or handle
Physical contact and simulated physical contact (eg, textual descriptions like “hug” or “backrub”) without consent or after a request to stop
Threats of violence, both physical and psychological
Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm
Deliberate intimidation
Stalking or following
Harassing photography or recording, including logging online activity for harassment purposes
Sustained disruption of discussion
Unwelcome sexual attention, including gratuitous or off-topic sexual images or behaviour
Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
Continued one-on-one communication after requests to cease
Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect others from intentional abuse
Publication of non-harassing private communication
We will not act on complaints regarding:
‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
Reasonable communication of boundaries, such as “leave me alone,” “please go away,” or “I’m not discussing this with you”
Refusal to explain or debate social justice concepts
Communicating in a ‘tone’ you don’t find congenial
Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions


This Code of Conduct builds upon: OpenCon Code of Conduct, https://www.opencon2018.org/code_of_conduct, http://2012.jsconf.us/#/about & The Ada Initiative & http://github.com/leftlogic/confcodeofconduct.com 
This work is licensed under a Creative Commons Attribution 3.0 Unported License

**Comment by Bubblbu** [comment]
CoC has now been added to the website: https://opencon-cascadia.github.io/coc

**Comment by dasaderi** [comment]
Great job, everyone!
